config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'
  devise_for :users
  resources :users
  resources :posts
  resources :comments
  resources :profiles
  resources :friendships

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :posts
  has_many :comments
  has_one :profile
  has_many :friendships
  has_many :friends, :through => :friendships
  accepts_nested_attributes_for :profile

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email, uniqueness: true
  validates_presence_of :password

  def full_name
    ([first_name, last_name] - ['']).compact.join(' ')
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @posts = Post.all.order("created_at DESC")
    @comments = Comment.all.order("created_at DESC")

  end
end

app/views/dashboard/index.html.erb
<%= link_to 'create new post', new_post_path %>

<% post_ids = current_user.friends.ids %>
<% post_ids.push(current_user.id) %>
<% post = @posts.where(user_id: post_ids)%>
<% post = post.paginate(:page => params[:page], :per_page => 4)%>


<% post.each do |post| %>
<div class="jumbotron">
  <!-- <p><%= post.title %></p> -->
  <% if post.user.profile.present? %>
  <div class="row">
    <div class="user_post_image"%>
      <%=link_to cl_image_tag(post.user.profile.profile_picture_url), profile_path(id: post.user_id)%>
    </div>
    <% end %>

    <h4><%= post.user.full_name %></h4>
  </div>
  <div class="post_image">
    <%= cl_image_tag(post.image_url)%>
  </div>
  <div class="post_body">
    <p><%= post.body %></p>
  </div>

  <% if @comments.where(post_id: post.id).present? %>
  <% post.comments.each do |comment| %>
  <div class='row'>
    <div class="user_comment_image"%>
      <%=link_to cl_image_tag(comment.user.profile.profile_picture_url), profile_path(id: comment.user.profile.user_id)%>
    </div>
    <div class="comment_body">
      <%= comment.body %>
    </div>
  </div>

  <% end %>
  <% end %>
  <% if post.user_id == current_user.id %>
  <p><%= link_to 'edit post', edit_post_path(id: post.id) %></p>
  <% end %>

  <div class="jumbotron">
    <%= render 'comments/form', post: post.id%>
  </div>
  <p><%= "created at: #{post.created_at.to_date}" %></p>
</div>
<% end %>
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info post %>
  </div>

  <%= will_paginate post, :container => false %>
</div>