config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'
  devise_for :users
  resources :users
  resources :posts
  resources :comments
  resources :profiles
  resources :friendships

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
require 'file_size_validator'

class Profile < ApplicationRecord
  mount_uploader :profile_picture_url, ImageUploader

  belongs_to :user

  validates_presence_of :date_of_birth
  validates_presence_of :gender
  validates_presence_of :street
  validates_presence_of :house_number
  validates_presence_of :zip_or_postal_code
  validates_presence_of :town
  validates_presence_of :country
  validates_presence_of :language
  validates_presence_of :profile_picture_url
  validates :profile_picture_url, :file_size => { :maximum => 10.megabytes.to_i  }

  GenderTypes = ["gender_neutral","Male", "Female"]

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
  end

  def new
    @profile = Profile.new
  end

  def create
    Profile.create(profile_params.merge(user_id: current_user.id))
    redirect_to root_path
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])

  if @profile.update_attributes(profile_params)
    flash[:success] = "Profile updated!"
    redirect_to root_path(current_user)
  else
    render action: :edit
  end
end


  def delete
  end

  private
  def profile_params
    params.require(:profile).permit(:date_of_birth, :gender, :street, :house_number, :zip_or_postal_code, :town, :country, :language, :profile_picture_url)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for @profile do |f| %>
  <%= f.input :date_of_birth, as: :date, :start_year => 1900 %>
  <%= f.input :gender, collection: ["Gender neutral", "Male", "Female"] %>
  <%= f.input :street %>
  <%= f.input :house_number %>
  <%= f.input :zip_or_postal_code %>
  <%= f.input :town %>
  <%= f.input :country %>
  <%= f.input :language, as: :select, collection: AVAILABLE_LANGUAGES.sort.map {|k,v| [v,k]}, label: "Default language" %>

  <%= f.file_field :profile_picture_url %>

  <%= f.button :submit %>
<% end %>

app/views/profiles/_profile.html.erb
<%= "hihihihi"%>

app/views/profiles/_show.html.erb
<h1><%= current_user.full_name %>
</h1>
<% user_profile = current_user.profile %>
<div class="profile_image">
  <% if user_profile.profile_picture_url.present? %>
<%= cl_image_tag(user_profile.profile_picture_url)%>
<% else %>
<% if user_profile.gender == "Female" %>
  <%= image_tag 'woman.jpg'%>
  <% elsif user_profile.gender == "Male"%>
  <%= image_tag 'man.png'%>
<% else %>
  <%= image_tag 'gender_neutral.png'%>
  <% end %>
  <% end %>
</div>
<br/>
<br/>
<p> Age: <%= ((user_profile.date_of_birth.to_date .. Date.today.to_date).count/365) %>
<p> Gender: <%= user_profile.gender %> </p>
<p>Street: <%= user_profile.street %></p>
<p>House number: <%= user_profile.house_number %></p>
<p>Zip or postal code: <%= user_profile.zip_or_postal_code %></p>
<p>Town: <%= user_profile.town %></p>
<p>Country: <%= user_profile.country %></p>
<p>Profile last updated at: <%= user_profile.created_at.to_date %></p>

<%= link_to "update profile", edit_profile_path(user_profile.id) %>

app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

app/views/profiles/delete.html.erb
<h1>Profiles#delete</h1>
<p>Find me in app/views/profiles/delete.html.erb</p>

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/index.html.erb
<h1>Profiles#index</h1>
<p>Find me in app/views/profiles/index.html.erb</p>

app/views/profiles/new.html.erb
<h1>Create your profile</h1>

<%= render 'profiles/form' %>

app/views/profiles/show.html.erb
<h1>Profile</h1>
<p label="hoi"><%= @profile.created_at.to_date %></p>
<p><%= @profile.street %></p>
<p><%= @profile.zip_or_postal_code %></p>
<div class="profile_image">
<%= cl_image_tag(@profile.profile_picture_url)%>
</div>
<% if current_user.friendships.ids.present? %>
<% friend = current_user.friendships.map(&:friend_id).include? @profile.user_id%>
  <% if friend%>
        <p><%=  link_to "delete friendship", friendship_path(id: current_user.friendships.where(friend_id: @profile.user_id).ids), :method => :delete %></p>
    <% else %>
      <div>
        <p><%=  link_to "add as friend" ,friendships_path(:friend_id => @profile.user_id, :user_id => current_user.id), :method => :post%></p>
      </div>
    <%end %>
  <% else %>
    <div>
      <p><%=  link_to "add as friend" ,friendships_path(:friend_id => @profile.user_id, :user_id => current_user.id), :method => :post%></p>
    </div>
    <% end %>