config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'
  devise_for :users
  resources :users
  resources :posts
  resources :comments
  resources :profiles
  resources :friendships

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-light navbar-light">
  <!-- Brand -->
  <%= image_tag '24rakno6gmuvcij93l48_bigger.png', class: 'img-responsive'  %>
  <a class="navbar-brand" <%=link_to 'Nedbook', root_path%></a>


  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Posts
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" <%= link_to 'Post', posts_path %></a>
          <a class="dropdown-item" <%= link_to 'New post', new_post_path%></a>
            </div>
          </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Users
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" <%= link_to 'Users', users_path %></a>
          <!-- <a class="dropdown-item" href="#">Something else here</a> -->
        </div>
      </li>
    </ul>
  </div

  <div class="collapse navbar-collapse" id="collapsibleNavbar">
  <ul class="nav navbar-nav navbar">
    <% if current_user.present?%>
    <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
    <% else %>
    <li><%= link_to "Login", new_user_session_path %></li>

    <% end%>
  </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title style="color:white; font-family:Cronos;">Nedbook</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<%= render 'layouts/navbar'%>
<body>
  <div class='container-fluid'>
    <% flash.each do |key, value| %>
    <%-
    # Convert devise keys to bootstrap keys
    key = :info if key == :notice
    key = :warning if key == :alert
    -%>
    <%= content_tag(:div, class: "flash alert alert-#{key}") do %>
    <%= button_tag '×', class: 'close', data: {dismiss: 'alert'} %>
    <% if value.is_a?(Hash) %>
    <%= value[:text] %>
    <% if value[:button] %>
    <div class="text-center"><%= link_to value[:button][:text], value[:button][:link], class: 'btn pull' %></div>
    <% end %>
    <% elsif value.is_a? Array %>
    <ul class="list-unstyled">
      <% value.each do |array_value| %>
      <%= content_tag :li, array_value %>
      <% end %>
    </ul>
    <% else %>
    <%= value %>
    <% end %>
    <% end %>
    <% end %>
    <div class='row'>
      <div class='col-md-3'>
        <div class="jumbotron">
          <% if current_user.present? && current_user.profile.blank? %>
          <p><%= link_to "Click here to complete your profile", new_profile_path%></p>
          <% elsif current_user.present? && !current_user.profile.blank? %>
          <%= render "profiles/show" %>
          <% end %>
        </div>

        <div class="jumbotron">
          <h1><%= "Friends" %> </h1>
          <% if current_user.present? %>
          <p><%= link_to "Search new friends", users_path%></p>
          <% current_user.friends.each do |friend| %>
          <div class="profile_image" %>
            <%= cl_image_tag(friend.profile.profile_picture_url) %>
          </div>
          <%= friend.full_name %>
          <% end %>
          <% end %>
        </div>
      </div>

      <div class='col-md-5'>
        <%= yield %>
      </div>

      <div class='col-md-2'>
        <div class="jumbotron">
          <%= "Something else like links, commercials, games e.o." %>
        </div>
      </div>

      <div class='col-md-2'>
        <div class="jumbotron">
          <%= "Something else like links, commercials, games e.o." %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>